#nullable enable

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanDevicesExtendDto.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-13</date>
// <summary>
// 设备扩展信息DTO
// </summary>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using Lean.Cus.Common.Paging;
using Lean.Cus.Common.Enums;

namespace Lean.Cus.Application.Dtos.Admin;

/// <summary>
/// 设备扩展信息查询条件
/// </summary>
public class LeanDevicesExtendQueryDto : PagedQuery
{
    /// <summary>
    /// 设备标识
    /// </summary>
    public string? DeviceId { get; set; }

    /// <summary>
    /// 设备名称
    /// </summary>
    public string? DeviceName { get; set; }

    /// <summary>
    /// 设备类型
    /// </summary>
    public LeanDeviceType? DeviceType { get; set; }

    /// <summary>
    /// IP地址
    /// </summary>
    public string? IpAddress { get; set; }

    /// <summary>
    /// 在线状态
    /// </summary>
    public LeanOnlineStatus? OnlineStatus { get; set; }

    /// <summary>
    /// 用户ID
    /// </summary>
    public long? UserId { get; set; }

    /// <summary>
    /// 最后在线时间范围开始
    /// </summary>
    public DateTime? LastOnlineTimeStart { get; set; }

    /// <summary>
    /// 最后在线时间范围结束
    /// </summary>
    public DateTime? LastOnlineTimeEnd { get; set; }
}

/// <summary>
/// 设备扩展信息DTO
/// </summary>
public class LeanDevicesExtendDto
{
    /// <summary>
    /// 主键
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// 设备标识
    /// </summary>
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// 设备名称
    /// </summary>
    public string DeviceName { get; set; } = string.Empty;

    /// <summary>
    /// 设备类型
    /// </summary>
    public LeanDeviceType DeviceType { get; set; }

    /// <summary>
    /// 操作系统
    /// </summary>
    public string? OperatingSystem { get; set; }

    /// <summary>
    /// 浏览器
    /// </summary>
    public string? Browser { get; set; }

    /// <summary>
    /// IP地址
    /// </summary>
    public string? IpAddress { get; set; }

    /// <summary>
    /// 地理位置
    /// </summary>
    public string? Location { get; set; }

    /// <summary>
    /// 最后在线时间
    /// </summary>
    public DateTime? LastOnlineTime { get; set; }

    /// <summary>
    /// 在线状态
    /// </summary>
    public LeanOnlineStatus OnlineStatus { get; set; }

    /// <summary>
    /// 用户ID
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    public DateTime CreateTime { get; set; }

    /// <summary>
    /// 更新时间
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}

/// <summary>
/// 设备登录信息更新DTO
/// </summary>
public class LeanDevicesExtendLoginUpdateDto
{
    /// <summary>
    /// 设备标识
    /// </summary>
    [Required(ErrorMessage = "设备标识不能为空")]
    [StringLength(100, ErrorMessage = "设备标识长度不能超过100个字符")]
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// 设备名称
    /// </summary>
    [Required(ErrorMessage = "设备名称不能为空")]
    [StringLength(200, ErrorMessage = "设备名称长度不能超过200个字符")]
    public string DeviceName { get; set; } = string.Empty;

    /// <summary>
    /// 设备类型
    /// </summary>
    [Required(ErrorMessage = "设备类型不能为空")]
    public LeanDeviceType DeviceType { get; set; }

    /// <summary>
    /// 操作系统
    /// </summary>
    [StringLength(200, ErrorMessage = "操作系统长度不能超过200个字符")]
    public string? OperatingSystem { get; set; }

    /// <summary>
    /// 浏览器
    /// </summary>
    [StringLength(200, ErrorMessage = "浏览器长度不能超过200个字符")]
    public string? Browser { get; set; }

    /// <summary>
    /// IP地址
    /// </summary>
    [StringLength(50, ErrorMessage = "IP地址长度不能超过50个字符")]
    public string? IpAddress { get; set; }

    /// <summary>
    /// 地理位置
    /// </summary>
    [StringLength(200, ErrorMessage = "地理位置长度不能超过200个字符")]
    public string? Location { get; set; }

    /// <summary>
    /// 用户ID
    /// </summary>
    [Required(ErrorMessage = "用户ID不能为空")]
    public long UserId { get; set; }
}

/// <summary>
/// 设备登出信息更新DTO
/// </summary>
public class LeanDevicesExtendLogoutUpdateDto
{
    /// <summary>
    /// 设备标识
    /// </summary>
    [Required(ErrorMessage = "设备标识不能为空")]
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// IP地址
    /// </summary>
    [StringLength(50, ErrorMessage = "IP地址长度不能超过50个字符")]
    public string? IpAddress { get; set; }
}

/// <summary>
/// 设备扩展信息导出DTO
/// </summary>
public class LeanDevicesExtendExportDto
{
    /// <summary>
    /// 设备标识
    /// </summary>
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// 设备名称
    /// </summary>
    public string DeviceName { get; set; } = string.Empty;

    /// <summary>
    /// 设备类型名称
    /// </summary>
    public string DeviceTypeName { get; set; } = string.Empty;

    /// <summary>
    /// 操作系统
    /// </summary>
    public string? OperatingSystem { get; set; }

    /// <summary>
    /// 浏览器
    /// </summary>
    public string? Browser { get; set; }

    /// <summary>
    /// IP地址
    /// </summary>
    public string? IpAddress { get; set; }

    /// <summary>
    /// 地理位置
    /// </summary>
    public string? Location { get; set; }

    /// <summary>
    /// 最后在线时间
    /// </summary>
    public DateTime? LastOnlineTime { get; set; }

    /// <summary>
    /// 在线状态名称
    /// </summary>
    public string OnlineStatusName { get; set; } = string.Empty;

    /// <summary>
    /// 用户ID
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    public DateTime CreateTime { get; set; }

    /// <summary>
    /// 更新时间
    /// </summary>
    public DateTime? UpdateTime { get; set; }
} 