//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="ILeanUserService.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-08</date>
// <summary>
// 用户服务接口
// </summary>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading.Tasks;
using Lean.Cus.Common.Enums;
using Lean.Cus.Domain.Entities.Admin;
using Lean.Cus.Application.Dtos.Admin;
using Lean.Cus.Common.Services;

namespace Lean.Cus.Application.IServices.Admin;

/// <summary>
/// 用户服务接口
/// </summary>
public interface ILeanUserService : ILeanService<LeanUser, LeanUserDto, LeanUserQueryDto, LeanUserCreateDto, LeanUserUpdateDto>
{
    /// <summary>
    /// 获取用户列表
    /// </summary>
    /// <param name="status">状态</param>
    /// <returns>用户列表</returns>
    Task<List<LeanUserDto>> GetListAsync(LeanEnabledStatus? status = null);
} 