//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="ILeanMenuService.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-08</date>
// <summary>
// 菜单服务接口
// </summary>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading.Tasks;
using Lean.Cus.Common.Enums;
using Lean.Cus.Domain.Entities.Admin;
using Lean.Cus.Application.Dtos.Admin;
using Lean.Cus.Common.Services;

namespace Lean.Cus.Application.IServices.Admin;

/// <summary>
/// 菜单服务接口
/// </summary>
public interface ILeanMenuService : ILeanService<LeanMenu, LeanMenuDto, LeanMenuQueryDto, LeanMenuCreateDto, LeanMenuUpdateDto>
{
    /// <summary>
    /// 获取菜单树
    /// </summary>
    /// <param name="status">状态</param>
    /// <returns>菜单树</returns>
    Task<List<LeanMenuTreeDto>> GetTreeAsync(LeanEnabledStatus? status = null);

    /// <summary>
    /// 获取角色菜单树
    /// </summary>
    /// <param name="roleId">角色ID</param>
    /// <returns>角色菜单树</returns>
    Task<List<LeanMenuDto>> GetRoleMenuTreeAsync(long roleId);

    /// <summary>
    /// 获取用户菜单树
    /// </summary>
    /// <param name="userId">用户ID</param>
    /// <returns>用户菜单树</returns>
    Task<List<LeanMenuDto>> GetUserMenuTreeAsync(long userId);

    /// <summary>
    /// 修改菜单状态
    /// </summary>
    /// <param name="menuId">菜单ID</param>
    /// <param name="status">状态</param>
    /// <returns>是否成功</returns>
    Task<bool> ChangeStatusAsync(long menuId, LeanEnabledStatus status);

    /// <summary>
    /// 导入菜单数据
    /// </summary>
    /// <param name="importDtos">导入的菜单数据列表</param>
    /// <returns>导入结果(成功数量,失败数量)</returns>
    Task<(int Success, int Fail)> ImportAsync(List<LeanMenuImportDto> importDtos);

    /// <summary>
    /// 导出菜单数据
    /// </summary>
    /// <param name="queryDto">查询条件</param>
    /// <returns>导出的菜单数据列表</returns>
    Task<List<LeanMenuExportDto>> ExportAsync(LeanMenuQueryDto queryDto);

    /// <summary>
    /// 获取导入模板
    /// </summary>
    /// <returns>导入模板数据</returns>
    Task<LeanMenuImportTemplateDto> GetImportTemplateAsync();
} 