//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanErrorLog.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 错误日志实体类
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;
using Lean.Cus.Domain.Entities;
using Lean.Cus.Common.Enums;

namespace Lean.Cus.Domain.Entities.Log;

/// <summary>
/// 错误日志实体
/// </summary>
[SugarTable("lean_mon_error_log", "错误日志表")]
[SugarIndex("idx_error_log_level", nameof(ErrorLevel), OrderByType.Asc)]
public class LeanErrorLog : LeanBaseEntity
{
    /// <summary>
    /// 错误级别（0：调试，1：信息，2：警告，3：错误，4：致命）
    /// </summary>
    [SugarColumn(ColumnName = "error_level", ColumnDescription = "错误级别（0：调试，1：信息，2：警告，3：错误，4：致命）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanErrorLevel ErrorLevel { get; set; }

    /// <summary>
    /// 错误来源
    /// </summary>
    [SugarColumn(ColumnName = "source", ColumnDescription = "错误来源", 
        Length = 200, IsNullable = false, ColumnDataType = "varchar")]
    public string Source { get; set; } = string.Empty;

    /// <summary>
    /// 错误消息
    /// </summary>
    [SugarColumn(ColumnName = "message", ColumnDescription = "错误消息", 
        Length = 4000, IsNullable = false, ColumnDataType = "nvarchar")]
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// 堆栈跟踪
    /// </summary>
    [SugarColumn(ColumnName = "stack_trace", ColumnDescription = "堆栈跟踪", 
        Length = 4000, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? StackTrace { get; set; }

    /// <summary>
    /// 内部异常
    /// </summary>
    [SugarColumn(ColumnName = "inner_exception", ColumnDescription = "内部异常", 
        Length = 4000, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? InnerException { get; set; }

    /// <summary>
    /// 请求URL
    /// </summary>
    [SugarColumn(ColumnName = "url", ColumnDescription = "请求URL", 
        Length = 500, IsNullable = true, ColumnDataType = "varchar")]
    public string? Url { get; set; }

    /// <summary>
    /// 请求方法
    /// </summary>
    [SugarColumn(ColumnName = "method", ColumnDescription = "请求方法", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? Method { get; set; }

    /// <summary>
    /// 请求参数
    /// </summary>
    [SugarColumn(ColumnName = "parameters", ColumnDescription = "请求参数", 
        Length = 4000, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Parameters { get; set; }

    /// <summary>
    /// 用户ID
    /// </summary>
    [SugarColumn(ColumnName = "user_id", ColumnDescription = "用户ID", 
        IsNullable = true, ColumnDataType = "bigint")]
    public long? UserId { get; set; }

    /// <summary>
    /// 用户名
    /// </summary>
    [SugarColumn(ColumnName = "user_name", ColumnDescription = "用户名", 
        Length = 50, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? UserName { get; set; }

    /// <summary>
    /// 请求IP
    /// </summary>
    [SugarColumn(ColumnName = "ip", ColumnDescription = "请求IP", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? Ip { get; set; }

    /// <summary>
    /// 浏览器
    /// </summary>
    [SugarColumn(ColumnName = "browser", ColumnDescription = "浏览器", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? Browser { get; set; }

    /// <summary>
    /// 操作系统
    /// </summary>
    [SugarColumn(ColumnName = "os", ColumnDescription = "操作系统", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? Os { get; set; }
} 