//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanOperationLog.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 操作日志实体类
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;
using Lean.Cus.Domain.Entities;
using Lean.Cus.Common.Enums;

namespace Lean.Cus.Domain.Entities.Log;

/// <summary>
/// 操作日志实体
/// </summary>
[SugarTable("lean_mon_operation_log", "操作日志表")]
[SugarIndex("idx_operation_log_user", nameof(UserId), OrderByType.Asc)]
[SugarIndex("idx_operation_log_type", nameof(OperationType), OrderByType.Asc)]
public class LeanOperationLog : LeanBaseEntity
{
    /// <summary>
    /// 用户ID
    /// </summary>
    [SugarColumn(ColumnName = "user_id", ColumnDescription = "用户ID", 
        IsNullable = false, ColumnDataType = "bigint")]
    public long UserId { get; set; }

    /// <summary>
    /// 用户名
    /// </summary>
    [SugarColumn(ColumnName = "user_name", ColumnDescription = "用户名", 
        Length = 50, IsNullable = false, ColumnDataType = "nvarchar")]
    public string UserName { get; set; } = string.Empty;

    /// <summary>
    /// 操作类型
    /// </summary>
    [SugarColumn(ColumnName = "operation_type", ColumnDescription = "操作类型", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanOperationType OperationType { get; set; }

    /// <summary>
    /// 操作描述
    /// </summary>
    [SugarColumn(ColumnName = "description", ColumnDescription = "操作描述", 
        Length = 500, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Description { get; set; }

    /// <summary>
    /// 请求方法
    /// </summary>
    [SugarColumn(ColumnName = "method", ColumnDescription = "请求方法", 
        Length = 50, IsNullable = false, ColumnDataType = "varchar")]
    public string Method { get; set; } = string.Empty;

    /// <summary>
    /// 请求URL
    /// </summary>
    [SugarColumn(ColumnName = "url", ColumnDescription = "请求URL", 
        Length = 500, IsNullable = false, ColumnDataType = "varchar")]
    public string Url { get; set; } = string.Empty;

    /// <summary>
    /// 请求参数
    /// </summary>
    [SugarColumn(ColumnName = "parameters", ColumnDescription = "请求参数", 
        Length = 4000, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Parameters { get; set; }

    /// <summary>
    /// 请求IP
    /// </summary>
    [SugarColumn(ColumnName = "ip", ColumnDescription = "请求IP", 
        Length = 50, IsNullable = false, ColumnDataType = "varchar")]
    public string Ip { get; set; } = string.Empty;

    /// <summary>
    /// 请求位置
    /// </summary>
    [SugarColumn(ColumnName = "location", ColumnDescription = "请求位置", 
        Length = 100, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Location { get; set; }

    /// <summary>
    /// 浏览器
    /// </summary>
    [SugarColumn(ColumnName = "browser", ColumnDescription = "浏览器", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? Browser { get; set; }

    /// <summary>
    /// 操作系统
    /// </summary>
    [SugarColumn(ColumnName = "os", ColumnDescription = "操作系统", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? Os { get; set; }

    /// <summary>
    /// 响应结果
    /// </summary>
    [SugarColumn(ColumnName = "result", ColumnDescription = "响应结果", 
        Length = 4000, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Result { get; set; }

    /// <summary>
    /// 执行时长（毫秒）
    /// </summary>
    [SugarColumn(ColumnName = "duration", ColumnDescription = "执行时长（毫秒）", 
        IsNullable = false, ColumnDataType = "int")]
    public int Duration { get; set; }

    /// <summary>
    /// 状态（0：失败，1：成功）
    /// </summary>
    [SugarColumn(ColumnName = "status", ColumnDescription = "状态（0：失败，1：成功）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanStatus Status { get; set; } = LeanStatus.Enabled;

    /// <summary>
    /// 错误信息
    /// </summary>
    [SugarColumn(ColumnName = "error_message", ColumnDescription = "错误信息", 
        Length = 4000, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? ErrorMessage { get; set; }
} 