//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanLoginLog.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 登录日志实体类
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;
using Lean.Cus.Domain.Entities;
using Lean.Cus.Common.Enums;

namespace Lean.Cus.Domain.Entities.Log;

/// <summary>
/// 登录日志实体
/// </summary>
[SugarTable("lean_mon_login_log", "登录日志表")]
[SugarIndex("idx_login_log_user", nameof(UserId), OrderByType.Asc)]
[SugarIndex("idx_login_log_status", nameof(Status), OrderByType.Asc)]
public class LeanLoginLog : LeanBaseEntity
{
    /// <summary>
    /// 用户ID
    /// </summary>
    [SugarColumn(ColumnName = "user_id", ColumnDescription = "用户ID", 
        IsNullable = false, ColumnDataType = "bigint")]
    public long UserId { get; set; }

    /// <summary>
    /// 用户名
    /// </summary>
    [SugarColumn(ColumnName = "user_name", ColumnDescription = "用户名", 
        Length = 50, IsNullable = false, ColumnDataType = "nvarchar")]
    public string UserName { get; set; } = string.Empty;

    /// <summary>
    /// 登录IP
    /// </summary>
    [SugarColumn(ColumnName = "ip", ColumnDescription = "登录IP", 
        Length = 50, IsNullable = false, ColumnDataType = "varchar")]
    public string Ip { get; set; } = string.Empty;

    /// <summary>
    /// 登录位置
    /// </summary>
    [SugarColumn(ColumnName = "location", ColumnDescription = "登录位置", 
        Length = 100, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Location { get; set; }

    /// <summary>
    /// 浏览器
    /// </summary>
    [SugarColumn(ColumnName = "browser", ColumnDescription = "浏览器", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? Browser { get; set; }

    /// <summary>
    /// 操作系统
    /// </summary>
    [SugarColumn(ColumnName = "os", ColumnDescription = "操作系统", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? Os { get; set; }

    /// <summary>
    /// 登录方式（0：账号密码，1：短信验证码，2：邮箱验证码，3：微信，4：QQ，5：钉钉）
    /// </summary>
    [SugarColumn(ColumnName = "login_type", ColumnDescription = "登录方式（0：账号密码，1：短信验证码，2：邮箱验证码，3：微信，4：QQ，5：钉钉）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanLoginType LoginType { get; set; }

    /// <summary>
    /// 登录状态（0：失败，1：成功）
    /// </summary>
    [SugarColumn(ColumnName = "status", ColumnDescription = "登录状态（0：失败，1：成功）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanStatus Status { get; set; } = LeanStatus.Enabled;

    /// <summary>
    /// 错误消息
    /// </summary>
    [SugarColumn(ColumnName = "error_message", ColumnDescription = "错误消息", 
        Length = 500, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? ErrorMessage { get; set; }
} 