//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanUserExtendController.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-13</date>
// <summary>
// 用户扩展信息控制器
// </summary>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using Lean.Cus.Application.Dtos.Admin;
using Lean.Cus.Application.Interfaces.Admin;
using Lean.Cus.Common.Models;
using Lean.Cus.Common.Paging;
using Microsoft.AspNetCore.Mvc;

namespace Lean.Cus.Api.Controllers.Admin;

/// <summary>
/// 用户扩展信息
/// </summary>
[Route("api/admin/[controller]")]
[ApiController]
public class LeanUserExtendController : ControllerBase
{
    private readonly ILeanUserExtendService _userExtendService;

    /// <summary>
    /// 初始化用户扩展信息控制器
    /// </summary>
    public LeanUserExtendController(ILeanUserExtendService userExtendService)
    {
        _userExtendService = userExtendService;
    }

    /// <summary>
    /// 获取用户扩展信息
    /// </summary>
    [HttpGet("{userId}")]
    public async Task<ActionResult<LeanApiResult<LeanUserExtendDto>>> Get(long userId)
    {
        var result = await _userExtendService.GetAsync(userId);
        return Ok(LeanApiResult<LeanUserExtendDto>.Ok(result));
    }

    /// <summary>
    /// 分页查询用户扩展信息
    /// </summary>
    [HttpGet]
    public async Task<ActionResult<LeanApiResult<PagedResults<LeanUserExtendDto>>>> GetPageList([FromQuery] LeanUserExtendQueryDto query)
    {
        var result = await _userExtendService.GetPagedListAsync(query);
        return Ok(LeanApiResult<PagedResults<LeanUserExtendDto>>.Ok(result));
    }

    /// <summary>
    /// 更新用户登录信息
    /// </summary>
    [HttpPut("login")]
    public async Task<ActionResult<LeanApiResult>> UpdateLoginInfo([FromBody] LeanUserExtendLoginUpdateDto input)
    {
        await _userExtendService.UpdateLoginInfoAsync(input);
        return Ok(LeanApiResult.Ok());
    }

    /// <summary>
    /// 更新用户登出信息
    /// </summary>
    [HttpPut("logout")]
    public async Task<ActionResult<LeanApiResult>> UpdateLogoutInfo([FromBody] LeanUserExtendLogoutUpdateDto input)
    {
        await _userExtendService.UpdateLogoutInfoAsync(input);
        return Ok(LeanApiResult.Ok());
    }

    /// <summary>
    /// 更新用户密码错误信息
    /// </summary>
    [HttpPut("password-error")]
    public async Task<ActionResult<LeanApiResult>> UpdatePasswordErrorInfo([FromBody] LeanUserExtendPasswordErrorUpdateDto input)
    {
        await _userExtendService.UpdatePasswordErrorInfoAsync(input);
        return Ok(LeanApiResult.Ok());
    }

    /// <summary>
    /// 导出用户扩展信息
    /// </summary>
    [HttpGet("export")]
    public async Task<IActionResult> Export([FromQuery] LeanUserExtendQueryDto query)
    {
        var result = await _userExtendService.ExportAsync(query);
        return File(result, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "user-extend.xlsx");
    }
} 