//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="ILeanUserExtendService.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-13</date>
// <summary>
// 用户扩展信息服务接口
// </summary>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using Lean.Cus.Application.Dtos.Admin;
using Lean.Cus.Common.Paging;

namespace Lean.Cus.Application.Interfaces.Admin;

/// <summary>
/// 用户扩展信息服务接口
/// </summary>
public interface ILeanUserExtendService
{
    /// <summary>
    /// 获取用户扩展信息
    /// </summary>
    Task<LeanUserExtendDto> GetAsync(long userId);

    /// <summary>
    /// 分页查询用户扩展信息
    /// </summary>
    Task<PagedResults<LeanUserExtendDto>> GetPagedListAsync(LeanUserExtendQueryDto query);

    /// <summary>
    /// 更新用户登录信息
    /// </summary>
    Task UpdateLoginInfoAsync(LeanUserExtendLoginUpdateDto input);

    /// <summary>
    /// 更新用户登出信息
    /// </summary>
    Task UpdateLogoutInfoAsync(LeanUserExtendLogoutUpdateDto input);

    /// <summary>
    /// 更新用户密码错误信息
    /// </summary>
    Task UpdatePasswordErrorInfoAsync(LeanUserExtendPasswordErrorUpdateDto input);

    /// <summary>
    /// 导出用户扩展信息
    /// </summary>
    Task<byte[]> ExportAsync(LeanUserExtendQueryDto query);
} 