//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="ILeanDevicesExtendService.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-13</date>
// <summary>
// 设备扩展信息服务接口
// </summary>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading.Tasks;
using Lean.Cus.Application.Dtos.Admin;
using Lean.Cus.Common.Paging;
using Lean.Cus.Common.Enums;

namespace Lean.Cus.Application.Interfaces.Admin;

/// <summary>
/// 设备扩展信息服务接口
/// </summary>
public interface ILeanDevicesExtendService
{
    /// <summary>
    /// 获取设备扩展信息
    /// </summary>
    Task<LeanDevicesExtendDto> GetAsync(string deviceId);

    /// <summary>
    /// 获取用户的设备列表
    /// </summary>
    Task<List<LeanDevicesExtendDto>> GetListByUserIdAsync(long userId);

    /// <summary>
    /// 分页查询设备扩展信息
    /// </summary>
    Task<PagedResults<LeanDevicesExtendDto>> GetPagedListAsync(LeanDevicesExtendQueryDto query);

    /// <summary>
    /// 更新设备登录信息
    /// </summary>
    Task UpdateLoginInfoAsync(LeanDevicesExtendLoginUpdateDto input);

    /// <summary>
    /// 更新设备登出信息
    /// </summary>
    Task UpdateLogoutInfoAsync(LeanDevicesExtendLogoutUpdateDto input);

    /// <summary>
    /// 更新设备在线状态
    /// </summary>
    Task UpdateOnlineStatusAsync(string deviceId, LeanOnlineStatus status);

    /// <summary>
    /// 导出设备扩展信息
    /// </summary>
    Task<byte[]> ExportAsync(LeanDevicesExtendQueryDto query);
} 