//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanRoleDepartment.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 角色-部门关系实体类（用于数据权限）
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;
using Lean.Cus.Domain.Entities;

namespace Lean.Cus.Domain.Entities.Admin;

/// <summary>
/// 角色-部门关系实体（用于数据权限）
/// </summary>
[SugarTable("lean_admin_role_department", "角色-部门关系表")]
[SugarIndex("IX_LeanRoleDepartment", nameof(RoleId), OrderByType.Asc, nameof(DepartmentId), OrderByType.Asc, true)]
public class LeanRoleDepartment : LeanBaseEntity
{
    /// <summary>
    /// 角色ID
    /// </summary>
    [SugarColumn(ColumnName = "role_id", ColumnDescription = "角色ID", 
        IsNullable = false, ColumnDataType = "bigint")]
    public long RoleId { get; set; }

    /// <summary>
    /// 部门ID
    /// </summary>
    [SugarColumn(ColumnName = "department_id", ColumnDescription = "部门ID", 
        IsNullable = false, ColumnDataType = "bigint")]
    public long DepartmentId { get; set; }
} 