//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanDevicesExtend.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-13</date>
// <summary>
// 设备扩展信息实体类
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;
using Lean.Cus.Common.Enums;

namespace Lean.Cus.Domain.Entities.Admin;

/// <summary>
/// 设备扩展信息实体
/// </summary>
[SugarTable("lean_admin_devices_extend", "设备扩展信息表")]
[SugarIndex("idx_device_id", nameof(DeviceId), OrderByType.Asc)]
public class LeanDevicesExtend : LeanBaseEntity
{
    /// <summary>
    /// 设备标识
    /// </summary>
    [SugarColumn(ColumnName = "device_id", ColumnDescription = "设备标识", 
        Length = 100, IsNullable = false, ColumnDataType = "varchar")]
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// 设备名称
    /// </summary>
    [SugarColumn(ColumnName = "device_name", ColumnDescription = "设备名称", 
        Length = 200, IsNullable = false, ColumnDataType = "nvarchar")]
    public string DeviceName { get; set; } = string.Empty;

    /// <summary>
    /// 设备类型（1：PC端，2：移动端，3：平板，99：其他）
    /// </summary>
    [SugarColumn(ColumnName = "device_type", ColumnDescription = "设备类型（1：PC端，2：移动端，3：平板，99：其他）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanDeviceType DeviceType { get; set; } = LeanDeviceType.PC;

    /// <summary>
    /// 操作系统
    /// </summary>
    [SugarColumn(ColumnName = "operating_system", ColumnDescription = "操作系统", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? OperatingSystem { get; set; }

    /// <summary>
    /// 浏览器
    /// </summary>
    [SugarColumn(ColumnName = "browser", ColumnDescription = "浏览器", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Browser { get; set; }

    /// <summary>
    /// IP地址
    /// </summary>
    [SugarColumn(ColumnName = "ip_address", ColumnDescription = "IP地址", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? IpAddress { get; set; }

    /// <summary>
    /// 地理位置
    /// </summary>
    [SugarColumn(ColumnName = "location", ColumnDescription = "地理位置", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Location { get; set; }

    /// <summary>
    /// 最后在线时间
    /// </summary>
    [SugarColumn(ColumnName = "last_online_time", ColumnDescription = "最后在线时间", 
        IsNullable = true, ColumnDataType = "datetime")]
    public DateTime? LastOnlineTime { get; set; }

    /// <summary>
    /// 在线状态（0：离线，1：在线，2：忙碌，3：离开）
    /// </summary>
    [SugarColumn(ColumnName = "online_status", ColumnDescription = "在线状态（0：离线，1：在线，2：忙碌，3：离开）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanOnlineStatus OnlineStatus { get; set; } = LeanOnlineStatus.Offline;

    /// <summary>
    /// 用户ID
    /// </summary>
    [SugarColumn(ColumnName = "user_id", ColumnDescription = "用户ID", 
        IsNullable = false, ColumnDataType = "bigint")]
    public long UserId { get; set; }
} 