//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanDepartment.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 部门实体类
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;
using Lean.Cus.Domain.Entities;
using Lean.Cus.Common.Enums;

namespace Lean.Cus.Domain.Entities.Admin;

/// <summary>
/// 部门实体
/// </summary>
[SugarTable("lean_admin_department", "部门表")]
[SugarIndex("idx_department_code", nameof(Code), OrderByType.Asc, true)]
public class LeanDepartment : LeanBaseEntity
{
    /// <summary>
    /// 部门编码
    /// </summary>
    [SugarColumn(ColumnName = "code", ColumnDescription = "部门编码", 
        Length = 50, IsNullable = false, ColumnDataType = "varchar")]
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// 部门名称
    /// </summary>
    [SugarColumn(ColumnName = "name", ColumnDescription = "部门名称", 
        Length = 50, IsNullable = false, ColumnDataType = "nvarchar")]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// 部门类型（0：公司，1：部门，2：团队）
    /// </summary>
    [SugarColumn(ColumnName = "department_type", ColumnDescription = "部门类型（0：公司，1：部门，2：团队）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanDepartmentType DepartmentType { get; set; } = LeanDepartmentType.Department;

    /// <summary>
    /// 父级ID
    /// </summary>
    [SugarColumn(ColumnName = "parent_id", ColumnDescription = "父级ID", 
        IsNullable = true, ColumnDataType = "bigint")]
    public long? ParentId { get; set; }

    /// <summary>
    /// 负责人ID
    /// </summary>
    [SugarColumn(ColumnName = "leader_id", ColumnDescription = "负责人ID", 
        IsNullable = true, ColumnDataType = "bigint")]
    public long? LeaderId { get; set; }

    /// <summary>
    /// 联系电话
    /// </summary>
    [SugarColumn(ColumnName = "phone", ColumnDescription = "联系电话", 
        Length = 20, IsNullable = true, ColumnDataType = "varchar")]
    public string? Phone { get; set; }

    /// <summary>
    /// 邮箱
    /// </summary>
    [SugarColumn(ColumnName = "email", ColumnDescription = "邮箱", 
        Length = 100, IsNullable = true, ColumnDataType = "varchar")]
    public string? Email { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    [SugarColumn(ColumnName = "sort", ColumnDescription = "排序", 
        IsNullable = false, ColumnDataType = "int")]
    public int Sort { get; set; }

    /// <summary>
    /// 状态（0：禁用，1：启用）
    /// </summary>
    [SugarColumn(ColumnName = "status", ColumnDescription = "状态（0：禁用，1：启用）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanStatus Status { get; set; } = LeanStatus.Enabled;

    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(ColumnName = "remark", ColumnDescription = "备注", 
        Length = 500, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Remark { get; set; }
} 