//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanRole.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 角色实体类
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;
using Lean.Cus.Domain.Entities;
using Lean.Cus.Common.Enums;

namespace Lean.Cus.Domain.Entities.Admin;

/// <summary>
/// 角色实体
/// </summary>
[SugarTable("lean_admin_role", "角色表")]
[SugarIndex("idx_role_code", nameof(RoleCode), OrderByType.Asc, true)]
public class LeanRole : LeanBaseEntity
{
    /// <summary>
    /// 角色编码
    /// </summary>
    [SugarColumn(ColumnName = "code", ColumnDescription = "角色编码", 
        Length = 50, IsNullable = false, ColumnDataType = "varchar")]
    public string RoleCode { get; set; } = string.Empty;

    /// <summary>
    /// 角色名称
    /// </summary>
    [SugarColumn(ColumnName = "name", ColumnDescription = "角色名称", 
        Length = 50, IsNullable = false, ColumnDataType = "nvarchar")]
    public string RoleName { get; set; } = string.Empty;

    /// <summary>
    /// 角色类型（0：系统角色，1：业务角色）
    /// </summary>
    [SugarColumn(ColumnName = "role_type", ColumnDescription = "角色类型（0：系统角色，1：业务角色）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanRoleType RoleType { get; set; } = LeanRoleType.System;

    /// <summary>
    /// 数据范围（0：全部数据，1：本部门数据，2：本部门及以下数据，3：自定义数据，4：仅本人数据）
    /// </summary>
    [SugarColumn(ColumnName = "data_scope", ColumnDescription = "数据范围（0：全部数据，1：本部门数据，2：本部门及以下数据，3：自定义数据，4：仅本人数据）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanDataScope DataScope { get; set; } = LeanDataScope.All;

    /// <summary>
    /// 排序号
    /// </summary>
    [SugarColumn(ColumnName = "order_num", ColumnDescription = "排序号", 
        IsNullable = false, ColumnDataType = "int")]
    public int OrderNum { get; set; }

    /// <summary>
    /// 状态（0：禁用，1：启用）
    /// </summary>
    [SugarColumn(ColumnName = "status", ColumnDescription = "状态（0：禁用，1：启用）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanStatus Status { get; set; } = LeanStatus.Enabled;

    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(ColumnName = "remark", ColumnDescription = "备注", 
        Length = 500, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Remark { get; set; }
} 