//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanUserExtend.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-13</date>
// <summary>
// 用户扩展信息实体类
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Lean.Cus.Domain.Entities.Admin;

/// <summary>
/// 用户扩展信息实体
/// </summary>
[SugarTable("lean_admin_user_extend", "用户扩展信息表")]
[SugarIndex("idx_user_id", nameof(UserId), OrderByType.Asc)]
public class LeanUserExtend : LeanBaseEntity
{
    /// <summary>
    /// 用户ID
    /// </summary>
    [SugarColumn(ColumnName = "user_id", ColumnDescription = "用户ID", 
        IsNullable = false, ColumnDataType = "bigint")]
    public long UserId { get; set; }

    #region 首次登录信息
    /// <summary>
    /// 首次登录时间
    /// </summary>
    [SugarColumn(ColumnName = "first_login_time", ColumnDescription = "首次登录时间", 
        IsNullable = true, ColumnDataType = "datetime")]
    public DateTime? FirstLoginTime { get; set; }

    /// <summary>
    /// 首次登录IP
    /// </summary>
    [SugarColumn(ColumnName = "first_login_ip", ColumnDescription = "首次登录IP", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? FirstLoginIp { get; set; }

    /// <summary>
    /// 首次登录设备
    /// </summary>
    [SugarColumn(ColumnName = "first_login_device", ColumnDescription = "首次登录设备", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? FirstLoginDevice { get; set; }

    /// <summary>
    /// 首次登录地点
    /// </summary>
    [SugarColumn(ColumnName = "first_login_location", ColumnDescription = "首次登录地点", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? FirstLoginLocation { get; set; }

    /// <summary>
    /// 首次登录浏览器
    /// </summary>
    [SugarColumn(ColumnName = "first_login_browser", ColumnDescription = "首次登录浏览器", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? FirstLoginBrowser { get; set; }

    /// <summary>
    /// 首次登录操作系统
    /// </summary>
    [SugarColumn(ColumnName = "first_login_os", ColumnDescription = "首次登录操作系统", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? FirstLoginOs { get; set; }
    #endregion

    #region 末次登录信息
    /// <summary>
    /// 末次登录时间
    /// </summary>
    [SugarColumn(ColumnName = "last_login_time", ColumnDescription = "末次登录时间", 
        IsNullable = true, ColumnDataType = "datetime")]
    public DateTime? LastLoginTime { get; set; }

    /// <summary>
    /// 末次登录IP
    /// </summary>
    [SugarColumn(ColumnName = "last_login_ip", ColumnDescription = "末次登录IP", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? LastLoginIp { get; set; }

    /// <summary>
    /// 末次登录设备
    /// </summary>
    [SugarColumn(ColumnName = "last_login_device", ColumnDescription = "末次登录设备", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? LastLoginDevice { get; set; }

    /// <summary>
    /// 末次登录地点
    /// </summary>
    [SugarColumn(ColumnName = "last_login_location", ColumnDescription = "末次登录地点", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? LastLoginLocation { get; set; }

    /// <summary>
    /// 末次登录浏览器
    /// </summary>
    [SugarColumn(ColumnName = "last_login_browser", ColumnDescription = "末次登录浏览器", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? LastLoginBrowser { get; set; }

    /// <summary>
    /// 末次登录操作系统
    /// </summary>
    [SugarColumn(ColumnName = "last_login_os", ColumnDescription = "末次登录操作系统", 
        Length = 200, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? LastLoginOs { get; set; }
    #endregion

    #region 末次登出信息
    /// <summary>
    /// 末次登出时间
    /// </summary>
    [SugarColumn(ColumnName = "last_logout_time", ColumnDescription = "末次登出时间", 
        IsNullable = true, ColumnDataType = "datetime")]
    public DateTime? LastLogoutTime { get; set; }

    /// <summary>
    /// 末次登出IP
    /// </summary>
    [SugarColumn(ColumnName = "last_logout_ip", ColumnDescription = "末次登出IP", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? LastLogoutIp { get; set; }

    /// <summary>
    /// 末次登出方式（主动登出/超时登出/强制登出）
    /// </summary>
    [SugarColumn(ColumnName = "last_logout_type", ColumnDescription = "末次登出方式（主动登出/超时登出/强制登出）", 
        Length = 50, IsNullable = true, ColumnDataType = "varchar")]
    public string? LastLogoutType { get; set; }
    #endregion

    #region 统计信息
    /// <summary>
    /// 登录总次数
    /// </summary>
    [SugarColumn(ColumnName = "login_count", ColumnDescription = "登录总次数", 
        IsNullable = false, DefaultValue = "0", ColumnDataType = "int")]
    public int LoginCount { get; set; }

    /// <summary>
    /// 密码错误次数
    /// </summary>
    [SugarColumn(ColumnName = "password_error_count", ColumnDescription = "密码错误次数", 
        IsNullable = false, DefaultValue = "0", ColumnDataType = "int")]
    public int PasswordErrorCount { get; set; }

    /// <summary>
    /// 最后密码错误时间
    /// </summary>
    [SugarColumn(ColumnName = "last_password_error_time", ColumnDescription = "最后密码错误时间", 
        IsNullable = true, ColumnDataType = "datetime")]
    public DateTime? LastPasswordErrorTime { get; set; }

    /// <summary>
    /// 锁定结束时间
    /// </summary>
    [SugarColumn(ColumnName = "lockout_end_time", ColumnDescription = "锁定结束时间", 
        IsNullable = true, ColumnDataType = "datetime")]
    public DateTime? LockoutEndTime { get; set; }
    #endregion
} 