//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanMenu.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-08</date>
// <summary>
// 菜单实体类
// </summary>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Lean.Cus.Common.Entities;
using Lean.Cus.Common.Enums;
using SqlSugar;

namespace Lean.Cus.Domain.Entities.Admin;

/// <summary>
/// 菜单实体
/// </summary>
/// <remarks>
/// 菜单是系统功能的组织单位，用于构建系统的导航结构和权限控制。
/// 支持多级菜单结构，通过ParentId构建树形层级关系。
/// 菜单类型包括：目录(1)、菜单(2)、按钮(3)。
/// 目录用于组织子菜单，菜单用于页面导航，按钮用于功能权限控制。
/// 每个菜单可以设置访问路由、组件路径、权限标识等信息。
/// 菜单可以启用或禁用，禁用的菜单不显示在导航中。
/// 系统菜单不允许删除，以保证系统的基本功能。
/// </remarks>
[SugarTable("lean_menu", "菜单表")]
[SugarIndex("idx_menu_parent_id", nameof(ParentId), OrderByType.Asc)]
[SugarIndex("idx_menu_code", nameof(Code), OrderByType.Asc, true)]
public class LeanMenu : LeanEntity
{
    /// <summary>
    /// 构造函数
    /// </summary>
    public LeanMenu()
    {
        Name = string.Empty;
        Code = string.Empty;
        Icon = string.Empty;
        Path = string.Empty;
        Component = string.Empty;
        Permission = string.Empty;
    }

    /// <summary>
    /// 父级ID
    /// </summary>
    /// <remarks>
    /// 数据类型：长整型（bigint）
    /// 允许为空：是
    /// 默认值：null
    /// 说明：上级菜单ID，顶级菜单的ParentId为null
    /// 已建立索引：idx_menu_parent_id
    /// 外键关系：lean_menu.id
    /// </remarks>
    [SugarColumn(ColumnName = "parent_id", ColumnDescription = "父级ID", IsNullable = true, ColumnDataType = "bigint")]
    public long? ParentId { get; set; }

    /// <summary>
    /// 菜单名称
    /// </summary>
    /// <remarks>
    /// 数据类型：字符串（nvarchar）
    /// 长度：50
    /// 允许为空：否
    /// 默认值：空字符串
    /// 说明：菜单的显示名称，支持多语言
    /// 建议使用易于理解的名称
    /// </remarks>
    [SugarColumn(ColumnName = "name", ColumnDescription = "菜单名称", Length = 50, IsNullable = false, ColumnDataType = "nvarchar")]
    public string Name { get; set; }

    /// <summary>
    /// 菜单编码
    /// </summary>
    /// <remarks>
    /// 数据类型：字符串（varchar）
    /// 长度：50
    /// 允许为空：否
    /// 默认值：空字符串
    /// 说明：菜单的唯一标识，系统中不允许重复
    /// 建议使用有意义的编码，如：system:user:list
    /// 已建立唯一索引：idx_menu_code
    /// </remarks>
    [SugarColumn(ColumnName = "code", ColumnDescription = "菜单编码", Length = 50, IsNullable = false, ColumnDataType = "varchar")]
    public string Code { get; set; }

    /// <summary>
    /// 菜单类型
    /// </summary>
    /// <remarks>
    /// 数据类型：整型（int）
    /// 允许为空：否
    /// 默认值：1
    /// 说明：菜单类型：目录(1)、菜单(2)、按钮(3)
    /// 目录用于组织子菜单，菜单用于页面导航，按钮用于功能权限控制
    /// </remarks>
    [SugarColumn(ColumnName = "type", ColumnDescription = "菜单类型", IsNullable = false, ColumnDataType = "int")]
    public LeanMenuType Type { get; set; }

    /// <summary>
    /// 图标
    /// </summary>
    /// <remarks>
    /// 数据类型：字符串（varchar）
    /// 长度：100
    /// 允许为空：否
    /// 默认值：空字符串
    /// 说明：菜单的图标，支持Font Awesome、Ant Design图标
    /// 建议选择符合功能特点的图标
    /// </remarks>
    [SugarColumn(ColumnName = "icon", ColumnDescription = "图标", Length = 100, IsNullable = false, ColumnDataType = "varchar")]
    public string Icon { get; set; }

    /// <summary>
    /// 路由地址
    /// </summary>
    /// <remarks>
    /// 数据类型：字符串（varchar）
    /// 长度：200
    /// 允许为空：否
    /// 默认值：空字符串
    /// 说明：访问菜单的路由地址
    /// 目录和菜单类型必须设置路由地址
    /// </remarks>
    [SugarColumn(ColumnName = "path", ColumnDescription = "路由地址", Length = 200, IsNullable = false, ColumnDataType = "varchar")]
    public string Path { get; set; }

    /// <summary>
    /// 组件路径
    /// </summary>
    /// <remarks>
    /// 数据类型：字符串（varchar）
    /// 长度：255
    /// 允许为空：否
    /// 默认值：空字符串
    /// 说明：菜单对应的前端组件路径
    /// 菜单类型必须设置组件路径
    /// </remarks>
    [SugarColumn(ColumnName = "component", ColumnDescription = "组件路径", Length = 255, IsNullable = false, ColumnDataType = "varchar")]
    public string Component { get; set; }

    /// <summary>
    /// 权限标识
    /// </summary>
    /// <remarks>
    /// 数据类型：字符串（varchar）
    /// 长度：100
    /// 允许为空：否
    /// 默认值：空字符串
    /// 说明：权限字符串，如：system:user:list
    /// 按钮类型必须设置权限标识
    /// </remarks>
    [SugarColumn(ColumnName = "permission", ColumnDescription = "权限标识", Length = 100, IsNullable = false, ColumnDataType = "varchar")]
    public string Permission { get; set; }

    /// <summary>
    /// 打开方式
    /// </summary>
    /// <remarks>
    /// 数据类型：整型（int）
    /// 允许为空：否
    /// 默认值：1
    /// 说明：菜单打开方式：组件内(1)、新窗口(2)、外链(3)
    /// 仅对菜单类型有效
    /// </remarks>
    [SugarColumn(ColumnName = "target", ColumnDescription = "打开方式", IsNullable = false, ColumnDataType = "int")]
    public LeanMenuTarget Target { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    /// <remarks>
    /// 数据类型：整型（int）
    /// 允许为空：否
    /// 默认值：0
    /// 说明：显示顺序，值越小越靠前
    /// 默认按此字段排序
    /// </remarks>
    [SugarColumn(ColumnName = "order_num", ColumnDescription = "排序", IsNullable = false, ColumnDataType = "int")]
    public int OrderNum { get; set; }

    /// <summary>
    /// 状态
    /// </summary>
    /// <remarks>
    /// 数据类型：整型（int）
    /// 允许为空：否
    /// 默认值：1
    /// 说明：菜单状态：启用(1)、禁用(0)
    /// 禁用的菜单不显示在导航中
    /// </remarks>
    [SugarColumn(ColumnName = "status", ColumnDescription = "状态", IsNullable = false, ColumnDataType = "int")]
    public LeanEnabledStatus Status { get; set; }

    /// <summary>
    /// 是否系统菜单
    /// </summary>
    /// <remarks>
    /// 数据类型：整型（int）
    /// 允许为空：否
    /// 默认值：0
    /// 说明：是否是系统内置菜单：是(1)、否(0)
    /// 系统菜单不允许删除，以保证系统的基本功能
    /// </remarks>
    [SugarColumn(ColumnName = "is_system", ColumnDescription = "是否系统菜单", IsNullable = false, ColumnDataType = "int")]
    public int IsSystem { get; set; }

    /// <summary>
    /// 是否可见
    /// </summary>
    /// <remarks>
    /// 数据类型：整型（int）
    /// 允许为空：否
    /// 默认值：1
    /// 说明：是否在导航菜单中显示：是(1)、否(0)
    /// 不可见的菜单不显示在导航中，但可以通过路由访问
    /// </remarks>
    [SugarColumn(ColumnName = "visible", ColumnDescription = "是否可见", IsNullable = false, ColumnDataType = "int")]
    public int Visible { get; set; }

    /// <summary>
    /// 是否缓存
    /// </summary>
    /// <remarks>
    /// 数据类型：整型（int）
    /// 允许为空：否
    /// 默认值：0
    /// 说明：是否缓存该页面：是(1)、否(0)
    /// 仅对菜单类型有效
    /// </remarks>
    [SugarColumn(ColumnName = "is_cache", ColumnDescription = "是否缓存", IsNullable = false, ColumnDataType = "int")]
    public int IsCache { get; set; }

    /// <summary>
    /// 备注
    /// </summary>
    /// <remarks>
    /// 数据类型：字符串（nvarchar）
    /// 长度：500
    /// 允许为空：是
    /// 默认值：null
    /// 说明：菜单的补充说明信息
    /// 最多500个字符
    /// </remarks>
    [SugarColumn(ColumnName = "remark", ColumnDescription = "备注", Length = 500, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Remark { get; set; }

    /// <summary>
    /// 子菜单列表
    /// </summary>
    /// <remarks>
    /// 导航属性：当前菜单的子菜单列表
    /// 关联类型：一对多
    /// 关联字段：ParentId
    /// 说明：通过ParentId关联到子菜单
    /// </remarks>
    [Navigate(NavigateType.OneToMany, nameof(ParentId))]
    public List<LeanMenu> Children { get; set; } = new();

    /// <summary>
    /// 角色菜单关联列表
    /// </summary>
    /// <remarks>
    /// 导航属性：菜单的角色关联列表
    /// 关联类型：一对多
    /// 关联字段：MenuId
    /// 说明：通过MenuId关联到角色菜单关联表
    /// </remarks>
    [Navigate(NavigateType.OneToMany, nameof(LeanRoleMenu.MenuId))]
    public List<LeanRoleMenu> RoleMenus { get; set; } = new();
} 