//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanUser.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 用户实体类
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;
using Lean.Cus.Domain.Entities;
using Lean.Cus.Common.Enums;

namespace Lean.Cus.Domain.Entities.Admin;

/// <summary>
/// 用户实体
/// </summary>
[SugarTable("lean_admin_user", "用户表")]
[SugarIndex("idx_user_username", nameof(UserName), OrderByType.Asc, true)]
public class LeanUser : LeanBaseEntity
{
    /// <summary>
    /// 用户名
    /// </summary>
    [SugarColumn(ColumnName = "user_name", ColumnDescription = "用户名", 
        Length = 50, IsNullable = false, ColumnDataType = "nvarchar")]
    public string UserName { get; set; } = string.Empty;

    /// <summary>
    /// 密码
    /// </summary>
    [SugarColumn(ColumnName = "password", ColumnDescription = "密码", 
        Length = 100, IsNullable = false, ColumnDataType = "varchar")]
    public string Password { get; set; } = string.Empty;

    /// <summary>
    /// 盐值
    /// </summary>
    [SugarColumn(ColumnName = "salt", ColumnDescription = "盐值", 
        Length = 100, IsNullable = false, ColumnDataType = "varchar")]
    public string Salt { get; set; } = string.Empty;

    /// <summary>
    /// 真实姓名
    /// </summary>
    [SugarColumn(ColumnName = "real_name", ColumnDescription = "真实姓名", 
        Length = 50, IsNullable = false, ColumnDataType = "nvarchar")]
    public string RealName { get; set; } = string.Empty;

    /// <summary>
    /// 英文名称
    /// </summary>
    [SugarColumn(ColumnName = "english_name", ColumnDescription = "英文名称", 
        Length = 50, IsNullable = false, ColumnDataType = "nvarchar")]
    public string EnglishName { get; set; } = string.Empty;

    /// <summary>
    /// 手机号码
    /// </summary>
    [SugarColumn(ColumnName = "mobile", ColumnDescription = "手机号码", 
        Length = 20, IsNullable = false, ColumnDataType = "varchar")]
    public string Mobile { get; set; } = string.Empty;

    /// <summary>
    /// 邮箱
    /// </summary>
    [SugarColumn(ColumnName = "email", ColumnDescription = "邮箱", 
        Length = 100, IsNullable = false, ColumnDataType = "varchar")]
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// 用户类型（0：超级管理员，1：管理员，2：系统用户，3：普通用户，4：访客，5：VIP用户）
    /// </summary>
    [SugarColumn(ColumnName = "user_type", ColumnDescription = "用户类型（0：超级管理员，1：管理员，2：系统用户，3：普通用户，4：访客，5：VIP用户）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanUserType UserType { get; set; } = LeanUserType.SuperAdmin;

    /// <summary>
    /// 状态（0：禁用，1：启用，2：锁定，3：过期，4：待审核，5：审核拒绝，6：注销）
    /// </summary>
    [SugarColumn(ColumnName = "status", ColumnDescription = "状态（0：禁用，1：启用，2：锁定，3：过期，4：待审核，5：审核拒绝，6：注销）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanUserStatus Status { get; set; } = LeanUserStatus.Enabled;

    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(ColumnName = "remark", ColumnDescription = "备注", 
        Length = 500, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Remark { get; set; }

    /// <summary>
    /// 用户扩展信息
    /// </summary>
    [Navigate(NavigateType.OneToOne, nameof(Id), nameof(LeanUserExtend.UserId))]
    public LeanUserExtend UserExtend { get; set; }

    /// <summary>
    /// 用户设备列表
    /// </summary>
    [Navigate(NavigateType.OneToMany, nameof(Id), nameof(LeanDevicesExtend.UserId))]
    public List<LeanDevicesExtend> UserDevices { get; set; }
} 