//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanUserPosition.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 用户-岗位关系实体类
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;
using Lean.Cus.Domain.Entities;

namespace Lean.Cus.Domain.Entities.Admin;

/// <summary>
/// 用户-岗位关系实体
/// </summary>
[SugarTable("lean_admin_user_position", "用户-岗位关系表")]
[SugarIndex("IX_LeanUserPosition", nameof(UserId), OrderByType.Asc, nameof(PositionId), OrderByType.Asc, true)]
public class LeanUserPosition : LeanBaseEntity
{
    /// <summary>
    /// 用户ID
    /// </summary>
    [SugarColumn(ColumnName = "user_id", ColumnDescription = "用户ID", 
        IsNullable = false, ColumnDataType = "bigint")]
    public long UserId { get; set; }

    /// <summary>
    /// 岗位ID
    /// </summary>
    [SugarColumn(ColumnName = "position_id", ColumnDescription = "岗位ID", 
        IsNullable = false, ColumnDataType = "bigint")]
    public long PositionId { get; set; }

    /// <summary>
    /// 是否主岗位
    /// </summary>
    [SugarColumn(ColumnName = "is_primary", ColumnDescription = "是否主岗位", 
        IsNullable = false, ColumnDataType = "bit")]
    public bool IsPrimary { get; set; }
} 