//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanPosition.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 岗位实体类
// </summary>
//------------------------------------------------------------------------------

using System;
using SqlSugar;
using Lean.Cus.Domain.Entities;
using Lean.Cus.Common.Enums;

namespace Lean.Cus.Domain.Entities.Admin;

/// <summary>
/// 岗位实体
/// </summary>
[SugarTable("lean_admin_position", "岗位表")]
[SugarIndex("idx_position_code", nameof(Code), OrderByType.Asc, true)]
public class LeanPosition : LeanBaseEntity
{
    /// <summary>
    /// 岗位编码
    /// </summary>
    [SugarColumn(ColumnName = "code", ColumnDescription = "岗位编码", 
        Length = 50, IsNullable = false, ColumnDataType = "varchar")]
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// 岗位名称
    /// </summary>
    [SugarColumn(ColumnName = "name", ColumnDescription = "岗位名称", 
        Length = 50, IsNullable = false, ColumnDataType = "nvarchar")]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// 岗位类型（0：高层，1：中层，2：基层，9：其他）
    /// </summary>
    [SugarColumn(ColumnName = "position_type", ColumnDescription = "岗位类型（0：高层，1：中层，2：基层，9：其他）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanPositionType PositionType { get; set; } = LeanPositionType.Junior;

    /// <summary>
    /// 部门ID
    /// </summary>
    [SugarColumn(ColumnName = "department_id", ColumnDescription = "部门ID", 
        IsNullable = false, ColumnDataType = "bigint")]
    public long DepartmentId { get; set; }

    /// <summary>
    /// 职责描述
    /// </summary>
    [SugarColumn(ColumnName = "duty", ColumnDescription = "职责描述", 
        Length = 500, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Duty { get; set; }

    /// <summary>
    /// 任职要求
    /// </summary>
    [SugarColumn(ColumnName = "requirement", ColumnDescription = "任职要求", 
        Length = 500, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Requirement { get; set; }

    /// <summary>
    /// 排序号
    /// </summary>
    [SugarColumn(ColumnName = "order_num", ColumnDescription = "排序号", 
        IsNullable = false, ColumnDataType = "int")]
    public int OrderNum { get; set; }

    /// <summary>
    /// 状态（0：禁用，1：启用）
    /// </summary>
    [SugarColumn(ColumnName = "status", ColumnDescription = "状态（0：禁用，1：启用）", 
        IsNullable = false, ColumnDataType = "int")]
    public LeanStatus Status { get; set; } = LeanStatus.Enabled;

    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(ColumnName = "remark", ColumnDescription = "备注", 
        Length = 500, IsNullable = true, ColumnDataType = "nvarchar")]
    public string? Remark { get; set; }
} 