//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanPositionType.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 职位类型枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 职位类型枚举
/// </summary>
public enum LeanPositionType
{
    /// <summary>
    /// 高层
    /// </summary>
    Senior = 1,

    /// <summary>
    /// 中层
    /// </summary>
    Middle = 2,

    /// <summary>
    /// 基层
    /// </summary>
    Junior = 3
} 