//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanRoleType.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 角色类型枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 角色类型枚举
/// </summary>
public enum LeanRoleType
{
    /// <summary>
    /// 系统角色
    /// </summary>
    System = 0,

    /// <summary>
    /// 业务角色
    /// </summary>
    Business = 1
} 