//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanLoginType.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 登录方式枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 登录方式枚举
/// </summary>
public enum LeanLoginType
{
    /// <summary>
    /// 账号密码
    /// </summary>
    Password = 0,

    /// <summary>
    /// 短信验证码
    /// </summary>
    Sms = 1,

    /// <summary>
    /// 邮箱验证码
    /// </summary>
    Email = 2,

    /// <summary>
    /// 微信
    /// </summary>
    WeChat = 3,

    /// <summary>
    /// QQ
    /// </summary>
    QQ = 4,

    /// <summary>
    /// 钉钉
    /// </summary>
    DingTalk = 5
} 