//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanDepartmentType.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 部门类型枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 部门类型枚举
/// </summary>
public enum LeanDepartmentType
{
    /// <summary>
    /// 公司
    /// </summary>
    Company = 0,

    /// <summary>
    /// 部门
    /// </summary>
    Department = 1,

    /// <summary>
    /// 团队
    /// </summary>
    Team = 2
} 