//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanAuditType.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 审计类型枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 审计类型枚举
/// </summary>
public enum LeanAuditType
{
    /// <summary>
    /// 数据变更
    /// </summary>
    Data = 0,

    /// <summary>
    /// 权限变更
    /// </summary>
    Permission = 1,

    /// <summary>
    /// 配置变更
    /// </summary>
    Configuration = 2,

    /// <summary>
    /// 安全变更
    /// </summary>
    Security = 3
} 