//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanMenuType.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 菜单类型枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 菜单类型枚举
/// </summary>
public enum LeanMenuType
{
    /// <summary>
    /// 目录
    /// </summary>
    Directory = 1,

    /// <summary>
    /// 菜单
    /// </summary>
    Menu = 2,

    /// <summary>
    /// 按钮
    /// </summary>
    Button = 3
} 