//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanOperationType.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 操作类型枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 操作类型枚举
/// </summary>
public enum LeanOperationType
{
    /// <summary>
    /// 其他
    /// </summary>
    Other = 0,

    /// <summary>
    /// 查询
    /// </summary>
    Query = 1,

    /// <summary>
    /// 新增
    /// </summary>
    Create = 2,

    /// <summary>
    /// 修改
    /// </summary>
    Update = 3,

    /// <summary>
    /// 删除
    /// </summary>
    Delete = 4,

    /// <summary>
    /// 导入
    /// </summary>
    Import = 5,

    /// <summary>
    /// 导出
    /// </summary>
    Export = 6,

    /// <summary>
    /// 上传
    /// </summary>
    Upload = 7,

    /// <summary>
    /// 下载
    /// </summary>
    Download = 8,

    /// <summary>
    /// 授权
    /// </summary>
    Grant = 9,

    /// <summary>
    /// 强退
    /// </summary>
    ForceLogout = 10,

    /// <summary>
    /// 生成代码
    /// </summary>
    GenCode = 11,

    /// <summary>
    /// 清空数据
    /// </summary>
    Clean = 12,

    /// <summary>
    /// 审批
    /// </summary>
    Approve = 13
} 