//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanOnlineStatus.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-13</date>
// <summary>
// 在线状态枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 在线状态枚举
/// </summary>
public enum LeanOnlineStatus
{
    /// <summary>
    /// 离线
    /// </summary>
    Offline = 0,

    /// <summary>
    /// 在线
    /// </summary>
    Online = 1,

    /// <summary>
    /// 忙碌
    /// </summary>
    Busy = 2,

    /// <summary>
    /// 离开
    /// </summary>
    Away = 3
} 