//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanOperationType.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 操作类型枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 操作类型枚举
/// </summary>
public enum LeanOperationType
{
    /// <summary>
    /// 新增
    /// </summary>
    Add = 1,

    /// <summary>
    /// 修改
    /// </summary>
    Update = 2,

    /// <summary>
    /// 删除
    /// </summary>
    Delete = 3,

    /// <summary>
    /// 查询
    /// </summary>
    Query = 4,

    /// <summary>
    /// 导入
    /// </summary>
    Import = 5,

    /// <summary>
    /// 导出
    /// </summary>
    Export = 6,

    /// <summary>
    /// 登录
    /// </summary>
    Login = 7,

    /// <summary>
    /// 退出
    /// </summary>
    Logout = 8,

    /// <summary>
    /// 其他
    /// </summary>
    Other = 9
} 