//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanDeviceType.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-13</date>
// <summary>
// 设备类型枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 设备类型枚举
/// </summary>
public enum LeanDeviceType
{
    /// <summary>
    /// PC端
    /// </summary>
    PC = 1,

    /// <summary>
    /// 移动端
    /// </summary>
    Mobile = 2,

    /// <summary>
    /// 平板
    /// </summary>
    Tablet = 3,

    /// <summary>
    /// 其他
    /// </summary>
    Other = 99
} 