//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件的所有修改。
// </auto-generated>
//
// <copyright file="LeanDataScope.cs" company="Lean365">
//     Copyright (c) Lean365. All rights reserved.
// </copyright>
// <author>Lean365</author>
// <date>2024-01-09</date>
// <summary>
// 数据范围枚举
// </summary>
//------------------------------------------------------------------------------

namespace Lean.Cus.Common.Enums;

/// <summary>
/// 数据范围枚举
/// </summary>
public enum LeanDataScope
{
    /// <summary>
    /// 全部数据权限
    /// </summary>
    All = 1,

    /// <summary>
    /// 自定义数据权限
    /// </summary>
    Custom = 2,

    /// <summary>
    /// 本部门数据权限
    /// </summary>
    Department = 3,

    /// <summary>
    /// 本部门及以下数据权限
    /// </summary>
    DepartmentAndBelow = 4,

    /// <summary>
    /// 仅本人数据权限
    /// </summary>
    Self = 5
} 