name: Update Changelog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # 允许手动触发
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git-changelog
    
    - name: Generate Changelog
      run: |
        git-changelog \
          --output CHANGELOG.md \
          --remote origin \
          --sections feat,fix,docs,style,refactor,perf,test,build,ci,chore,revert \
          --template keepachangelog \
          --commit-style angular \
          --timezone Asia/Shanghai
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CHANGELOG.md
        git diff --quiet && git diff --staged --quiet || git commit -m "docs: 自动更新CHANGELOG [skip ci]"
        git push 